[package]
name = "ncoding"
version = "0.1.0"
authors = ["Noah Willingham <noahwillingham5@gmail.com>", "Charlie Harrison <harrisonc17@clystvale.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]